### ISSUE TITLE
requirments installation error

### ISSUE THREAD

**Issue by Ali-Flt** [soft-nougat/dqw-ivves#62]
I'm using python 3.9.12 and the requirements installation encounters errors.
First I was on python 3.10 and installing scipy version 1.5.4 encountered errors.
Then I rolled back to 3.9.12 but now pycaret doesn't install. 
Please update the requirments.txt

**Comment by soft-nougat** [comment]
Hey @Ali-Flt!

It is unclear to me what I need to change exactly. Can you provide the error message you are getting?

**Comment by Ali-Flt** [comment]
Hi @soft-nougat 
I don't know whether this is a pycaret bug or not but pycaret won't install on Python 3.9.13. It seems like it has `scikit-learn-0.23.2` in its dependencies for some reason which is odd.
Here is a full log of installing the `requirements.txt`:
[log.txt](https://github.com/soft-nougat/dqw-ivves/files/8871240/log.txt)


What is the supported Python version of your app?

**Comment by Ali-Flt** [comment]
Update: I tried with Python 3.8.13 and requirments.txt installs successfully but I can't run app.py:
```
$ streamlit app.py 
2022-06-09 19:06:09.518 INFO    numexpr.utils: NumExpr defaulting to 4 threads.
Usage: streamlit [OPTIONS] COMMAND [ARGS]...
Try 'streamlit --help' for help.

Error: No such command 'app.py'.
```

```
$ streamlit run app.py 
2022-06-09 19:06:18.202 INFO    numexpr.utils: NumExpr defaulting to 4 threads.
Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/devEnv_3.8/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/streamlit/cli.py", line 194, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/streamlit/cli.py", line 215, in _main_run
    command_line = _get_command_line_as_string()
  File "/home/ali/anaconda3/envs/devEnv_3.8/lib/python3.8/site-packages/streamlit/cli.py", line 204, in _get_command_line_as_string
    cmd_line_as_list.extend(click.get_os_args())
AttributeError: module 'click' has no attribute 'get_os_args'
```

**Comment by Ali-Flt** [comment]
Update: I think the issue is with streamlit version in [requirments.txt](https://github.com/soft-nougat/dqw-ivves/blob/master/requirements.txt) (1.4.0).
I ran `pip install streamlit --upgrade` and streamlit updated to 1.10.0 and now the app runs using `streamlit run app.py`

Summary: 
App runs using Python 3.8 and streamlit 1.10.0. Also in readme it says to use `streamlit app.py` but I think it should be `streamlit run app.py` instead.

**Comment by soft-nougat** [comment]
Hey @Ali-Flt!

Thanks for the feedback - I've just made the changes you highlighted. 
Please reopen the issue if there's anything I missed! :)
